[package]
name = "rope"
description = "a libary for simple cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strand-derive = { path = "./strand-derive", version = "0.1.0"}
bundle-derive = { path = "./bundle-derive", version = "0.1.0"}